version: "3"

services:
  myapp:
   image: janguni/algorithm-project-docker-repo:1.0
   ports:
     - 8080:8080
   volumes:
     - ./algorithmQNA_backend/build/libs:/build/libs
   depends_on:
     - redis
  redis:
    image: redis:latest
    container_name: redis_boot
    command: redis-server --port 6379
    hostname: admin
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
