name: AWS EC2 INSTANCE CI/CD 
######### master branch에 push 되었을때만 실행#########
on: 
  push:            
    branches: main
    
######### master branch에 push 되었을때만 실행#########

jobs:
  build: # job 이름 : build
    runs-on: ubuntu-latest # runner 운영체제
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
      ## create application-dev.properties

      - uses: actions/checkout@v3
      - run: ls -al src/main/
      - run: ls -al src/main/resources
      - run: touch src/main/resources/application.yml
      - run: echo "${{ secrets.PROPERTIES }}" > src/main/resources/application.yml
      - run: cat src/main/resources/application.yml
        
      ## gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test
        
      ## docker build & push to production
      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/algorithmdocker .
          docker push ${{ secrets.DOCKER_REPO }}/algorithmdocker
          
     ## deploy to develop
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: 
            pwd
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/algorithmdocker
            docker-compose up -d
            docker image prune -f
