name: AWS EC2 INSTANCE CI/CD 
######### master branch에 push 되었을때만 실행#########
on: 
  push:            
    branches: main
    
######### master branch에 push 되었을때만 실행#########

jobs:
  build: # job 이름 : build
    runs-on: ubuntu-latest # runner 운영체제
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
      ## create application-dev.properties
      - name: make application.properties
        if: contains(github.ref, 'develop')
        run: |
            cd ./src/main/resources
            touch ./application.properties
            echo "${{ secrets.PROPERTIES }}" > ./application-dev.properties
        shell: bash
        
      ## gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test
        
      ## docker build & push to production
      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod -t ${{ secrets.DOCKER_REPO }}/dotoriham-prod .
          docker push ${{ secrets.DOCKER_REPO }}/dotoriham-prod
